# .github/workflows/sql_analyzer.yml
name: SQL Analyzer CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  analyze-sql:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: dvdrental
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Docker image
        run: docker build -t sql-analyzer:ci .

      - name: Run SQL Analyzer CLI
        run: |
          source venv/bin/activate
          python cli.py --dsn "host=localhost dbname=dvdrental user=postgres password=postgres" --pgstat
